spring:
  application:
    name: user-management
#Enable below commented lines to use postgress as databases,currently H2 in-memeory database is enabled
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    generate-ddl: true
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/user-management
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

server:
  port: 9999